### ISSUE TITLE
What are 5-shot 5-way Reptile + Transduction hyperparameters?

### ISSUE THREAD

**Issue by glogowski-wojciech** [openai/supervised-reptile#15]
In https://arxiv.org/abs/1803.02999 you show results for 5-shot 5-way Reptile + Transduction. There is no such configuration in README though. Could you share hyperparameters used for transductive 5-shot 5-way?

**Comment by unixpickle** [comment]
See table 4 in appendix A. The 5-shot 5-way hyper-parameters were the same with and without transduction. Here is the command:

python -u run_miniimagenet.py --inner-batch 10 --inner-iters 8 --meta-step
1 --meta-batch 5 --meta-iters 100000 --eval-batch 15 --eval-iters 50
--learning-rate 0.001 --meta-step-final 0 --train-shots 15 --transductive
