### ISSUE TITLE
Having a summary of the model in readme would be helpful

### ISSUE THREAD

**Issue by Mirodil** [openai/supervised-reptile#2]
Hello,

It would be nice to have a summary of the model, visual representation of the model in readme file.

**Comment by unixpickle** [comment]
Would it be enough to link to the paper? Is there anything you think the readme should mention that's not in the paper?

**Comment by Mirodil** [comment]
The original paper is good. When you see the network architecture it is like self-explanatory how everything set up. btw I'm new in ML.
