### ISSUE TITLE
Typo in Algorithm 2 of the paper

### ISSUE THREAD

**Issue by shihux** [openai/supervised-reptile#4]
Hi, I think there is typo on the second to last line of Algorithm 2 on page 3 of this paper https://arxiv.org/abs/1803.02999 (March 8 version). Should it be 1 over **n** instead of **k**, since we're averaging over tasks rather than sgd steps?

**Comment by unixpickle** [comment]
Good catch--this is indeed a typo. We will fix this shortly.
