### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by nattari** [openai/supervised-reptile#5]
When i run the below command,
python -u run_omniglot.py --shots 1 --inner-batch 25 --inner-iters 3 --meta-step 1 --meta-batch 10 --meta-iters 100000 --eval-batch 25 --eval-iters 5 --learning-rate 0.001 --meta-step-final 0 --train-shots 15 --checkpoint ckpt_o15t --transductive

I get this error:
Traceback (most recent call last):
  File "run_omniglot.py", line 9, in <module>
    from supervised_reptile.args import argument_parser, model_kwargs, train_kwargs, evaluate_kwargs
  File "/Users/nazu/meta_learning/supervised-reptile/supervised_reptile/args.py", line 10, in <module>
    from .reptile import Reptile, FOML
  File "/Users/nazu/meta_learning/supervised-reptile/supervised_reptile/reptile.py", line 149
    def __init__(self, *args, tail_shots=None, **kwargs):
                                       ^
SyntaxError: invalid syntax

The python version I am using is 'Python 2.7.13' and tensorflow 1.6.0
Can you please tell me how can I possibly solve the error?

TIA

**Comment by unixpickle** [comment]
This code requires Python 3. I suggest using something like anaconda to get the latest version.

**Comment by nattari** [comment]
Thank you! It worked.
